### ISSUE TITLE
Q-Boid Crashing Server

### ISSUE THREAD

**Issue by Lmmb74** [CoWinkKeyDinkInc/CardinalPGM-Maps#19]
Welp, Q-Boid actually crashes my server, being this the crash log:

> java.lang.Error
> 
>   at in.twizmwaz.cardinal.module.modules.regions.type.CuboidRegion.getBlocks(CuboidRegion.java:81)
>   at in.twizmwaz.cardinal.module.modules.regions.type.combinations.UnionRegion.getBlocks(UnionRegion.java:63)
>   at in.twizmwaz.cardinal.module.modules.hill.HillObjective.renderBlocks(HillObjective.java:295)
>   at in.twizmwaz.cardinal.module.modules.hill.HillObjective.<init>(HillObjective.java:95)
>   at in.twizmwaz.cardinal.module.modules.hill.HillObjectiveBuilder.parseHill(HillObjectiveBuilder.java:99)
>   at in.twizmwaz.cardinal.module.modules.hill.HillObjectiveBuilder.load(HillObjectiveBuilder.java:33)
>   at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:228)
>   at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:55)
>   at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:57)
>   at in.twizmwaz.cardinal.GameHandler$1.run(GameHandler.java:40)
>   at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
>   at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
>   at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:705)
>   at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:365)
>   at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:666)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:570)
>   at java.lang.Thread.run(Unknown Source)

**Comment by Prodigy4532** [comment]
Send the full log with 'hastebin.com'

**Comment by Lmmb74** [comment]
Ok

**Comment by Lmmb74** [comment]
Welp, here it is:
http://pastebin.com/qucWJ1GB

**Comment by Lmmb74** [comment]
I will close this myself because I know it is caused by the high amount of hills trying to be loaded. So, this map (at least from KotH) should (indeed, MUST) be removed from this repo. Or maybe modify it (I will do it actually) to have less hills. Also, the hills and the default spawn aren't configurated well.

**Comment by CoWinkKeyDinkInc** [comment]
I had tried to load my map, and it has crashed too, it never came to me that it could be from too many hills strangely!  I will make a smaller version of the map or try to figure out how to reduce the hills.  Since this issue is still ongoing, the issue will be reopened.

**Comment by CoWinkKeyDinkInc** [comment]
Map renamed and hills 4-28 disabled in 3daa706bbd967dba6e257a14691adaecfaccc32c

**Comment by Lmmb74** [comment]
See? XD
Actually, I am making a working Q-Boid, but I am updating many of the maps in my fork, as well as fixing bugs and implementing features. Go check it: https://github.com/Lmmb74/CardinalPGM-Maps
But I will not make a pull request until I'm sure I solved the most possible. Also, I am organizing the xml files in order to make them easier to edit ;).

**Comment by Lmmb74** [comment]
Btw, many of the hills are not actually correctly set up so I will work on them, but my fork has a working version :D
